### ISSUE TITLE
This plugin is not compatible with the IDEA which version is 2020.1.1

### ISSUE THREAD

**Issue by 3dot141** [elitegit/asm-intellij-plugin#4]
java.lang.RuntimeException: Can't find icon in 'actions/diffWithCurrent.png' near PluginClassLoader[ASM Bytecode Viewer, 7.2] com.intellij.ide.plugins.cl.PluginClassLoader@69723831
	at com.intellij.openapi.util.IconLoader$CachedImageIcon$HandleNotFound$1.handle(IconLoader.java:822)

**Comment by YangLang116** [comment]
@3dot141  https://github.com/YangLang116/asm-intellij-plugin/blob/feature-compatible2021/ASM%20Bytecode%20Viewer-7.3.zip
